# Generated by Django 6.0.3 on 2026-10-01 07:57

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DietFood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="diet.dietsection",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DietEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="diet.dietfood",
                    ),
                ),
            ],
            options={
                "ordering": ["performed_on", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "performed_on"], name="diet_user_day_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "food", "performed_on"),
                        name="unique_daily_diet_entry",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dietsection",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_diet_section_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="dietfood",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("section"),
                name="unique_diet_food_name",
            ),
        ),
    ]
