# Generated by Django 6.0.3 on 2026-03-17 10:02

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.users.models.EncryptedEmailField(max_length=254),
        ),
    ]
