import uuid

from django.conf import settings
from django.db import models


class WearableConnection(models.Model):
    class Provider(models.TextChoices):
        HEALTH_CONNECT = "health_connect", "Health Connect"

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONNECTED = "connected", "Connected"
        DISCONNECTED = "disconnected", "Disconnected"
        ERROR = "error", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="wearable_connections",
    )
    provider = models.CharField(max_length=32, choices=Provider.choices)
    status = models.CharField(
        max_length=32,
        choices=Status.choices,
        default=Status.PENDING,
    )
    last_synced_at = models.DateTimeField(null=True, blank=True)
    last_error = models.TextField(blank=True, default="")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "wearables_wearable_connection"
        indexes = [
            models.Index(
                fields=["user", "provider", "status"],
                name="wear_conn_user_provider_status",
            ),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["user", "provider"],
                name="wear_conn_unique_user_provider",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.user_id}:{self.provider}:{self.status}"


class SyncRun(models.Model):
    class Status(models.TextChoices):
        RECEIVED = "received", "Received"
        PROCESSING = "processing", "Processing"
        SUCCEEDED = "succeeded", "Succeeded"
        PARTIAL = "partial", "Partial"
        FAILED = "failed", "Failed"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    wearable_connection = models.ForeignKey(
        WearableConnection,
        on_delete=models.CASCADE,
        related_name="sync_runs",
    )

    # Generated by the Android client and reused when retrying the same batch.
    upload_id = models.UUIDField()
    # SHA-256 of normalized entries; blank only on historical receipt rows.
    payload_hash = models.CharField(max_length=64, blank=True, default="")
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.RECEIVED,
    )

    received_at = models.DateTimeField(auto_now_add=True)
    processing_started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)
    entries_imported = models.PositiveIntegerField(default=0)
    entries_updated = models.PositiveIntegerField(default=0)
    entries_skipped = models.PositiveIntegerField(default=0)
    error_code = models.CharField(max_length=100, blank=True, default="")
    error_detail = models.JSONField(default=dict, blank=True)
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        db_table = "wearables_sync_run"
        constraints = [
            models.UniqueConstraint(
                fields=["wearable_connection", "upload_id"],
                name="wear_sync_unique_conn_upload",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"{self.wearable_connection_id}:"
            f"{self.upload_id}:"
            f"{self.status}"
        )
