# Generated by Django 6.0.3 on 2026-06-08 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active_custom_metric_limit', models.PositiveIntegerField()),
                ('wearable_connection_limit', models.PositiveIntegerField()),
                ('sync_interval_minutes', models.PositiveIntegerField()),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('csv_import_enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_subscription_plan',
            },
        ),
    ]
