# Generated by Django 6.0.3 on 2026-06-09 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_seed_free_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due', 'incomplete'])), fields=('user',), name='unique_current_subscription_per_user'),
        ),
    ]
