# Generated by Django 6.0.3 on 2026-06-11 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_unique_current_subscription_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=32)),
                ('provider_price_id', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('unit_amount', models.PositiveIntegerField()),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions_subscription_price',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionprice'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plan', 'provider', 'currency', 'billing_interval'), name='unique_active_price_per_plan_option'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionprice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gt', 0)), name='subscription_price_amount_above_zero'),
        ),
    ]
