# Generated by Django 6.0.3 on 2026-06-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutattempt',
            name='expected_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_attempts', to='subscriptions.subscription'),
        ),
    ]
