# Generated by Django 6.0.3 on 2026-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_billingcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
