# Generated by Django 6.0.3 on 2026-07-16 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0005_wearableconnection_pending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('entries_imported', models.PositiveIntegerField(default=0)),
                ('entries_skipped', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_detail', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wearable_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='wearables.wearableconnection')),
            ],
            options={
                'db_table': 'wearables_sync_run',
                'constraints': [models.UniqueConstraint(fields=('wearable_connection', 'upload_id'), name='wear_sync_unique_conn_upload')],
            },
        ),
    ]
