/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsConsistencyRouteImport } from './routes/analytics.consistency'
import { Route as AnalyticsSleepRouteImport } from './routes/analytics.sleep'
import { Route as AnalyticsWeightStepsRouteImport } from './routes/analytics.weight-steps'
import { Route as MetricsSlugRouteImport } from './routes/metrics.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsConsistencyRoute = AnalyticsConsistencyRouteImport.update({
  id: '/analytics/consistency',
  path: '/analytics/consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSleepRoute = AnalyticsSleepRouteImport.update({
  id: '/analytics/sleep',
  path: '/analytics/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsWeightStepsRoute = AnalyticsWeightStepsRouteImport.update({
  id: '/analytics/weight-steps',
  path: '/analytics/weight-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsSlugRoute = MetricsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MetricsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/analytics/consistency': typeof AnalyticsConsistencyRoute
  '/analytics/sleep': typeof AnalyticsSleepRoute
  '/analytics/weight-steps': typeof AnalyticsWeightStepsRoute
  '/metrics/$slug': typeof MetricsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/analytics/consistency': typeof AnalyticsConsistencyRoute
  '/analytics/sleep': typeof AnalyticsSleepRoute
  '/analytics/weight-steps': typeof AnalyticsWeightStepsRoute
  '/metrics/$slug': typeof MetricsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/analytics/consistency': typeof AnalyticsConsistencyRoute
  '/analytics/sleep': typeof AnalyticsSleepRoute
  '/analytics/weight-steps': typeof AnalyticsWeightStepsRoute
  '/metrics/$slug': typeof MetricsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/analytics/consistency'
    | '/analytics/sleep'
    | '/analytics/weight-steps'
    | '/metrics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/analytics/consistency'
    | '/analytics/sleep'
    | '/analytics/weight-steps'
    | '/metrics/$slug'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/analytics/consistency'
    | '/analytics/sleep'
    | '/analytics/weight-steps'
    | '/metrics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  AnalyticsConsistencyRoute: typeof AnalyticsConsistencyRoute
  AnalyticsSleepRoute: typeof AnalyticsSleepRoute
  AnalyticsWeightStepsRoute: typeof AnalyticsWeightStepsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/consistency': {
      id: '/analytics/consistency'
      path: '/analytics/consistency'
      fullPath: '/analytics/consistency'
      preLoaderRoute: typeof AnalyticsConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/sleep': {
      id: '/analytics/sleep'
      path: '/analytics/sleep'
      fullPath: '/analytics/sleep'
      preLoaderRoute: typeof AnalyticsSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/weight-steps': {
      id: '/analytics/weight-steps'
      path: '/analytics/weight-steps'
      fullPath: '/analytics/weight-steps'
      preLoaderRoute: typeof AnalyticsWeightStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$slug': {
      id: '/metrics/$slug'
      path: '/$slug'
      fullPath: '/metrics/$slug'
      preLoaderRoute: typeof MetricsSlugRouteImport
      parentRoute: typeof MetricsRoute
    }
  }
}

interface MetricsRouteChildren {
  MetricsSlugRoute: typeof MetricsSlugRoute
}

const MetricsRouteChildren: MetricsRouteChildren = {
  MetricsSlugRoute: MetricsSlugRoute,
}

const MetricsRouteWithChildren =
  MetricsRoute._addFileChildren(MetricsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  AnalyticsConsistencyRoute: AnalyticsConsistencyRoute,
  AnalyticsSleepRoute: AnalyticsSleepRoute,
  AnalyticsWeightStepsRoute: AnalyticsWeightStepsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
