# Generated by Django 6.0.3 on 2026-10-01 10:31

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_user_sleep_target_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutCatalogState",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("initialized_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("strength", "Weight and reps"),
                            ("bodyweight", "Reps with optional load"),
                            ("duration", "Duration"),
                            ("cardio", "Distance and duration"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lb", "lb")], default="kg", max_length=3
                    ),
                ),
                (
                    "distance_unit",
                    models.CharField(
                        choices=[("km", "km"), ("mi", "mi")], default="km", max_length=3
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "weight_increment",
                    models.DecimalField(decimal_places=3, default="2.5", max_digits=7),
                ),
                ("rest_seconds", models.PositiveIntegerField(default=90)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.exercisecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="exercisecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_exercise_category_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("category"),
                name="unique_exercise_name",
            ),
        ),
    ]
