# Generated by Django 6.0.3 on 2026-10-01 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("performed_on", models.DateField()),
                ("name", models.CharField(default="Workout", max_length=120)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("is_finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_on", "-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exercise_name", models.CharField(max_length=120)),
                ("category_name", models.CharField(max_length=120)),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("strength", "Weight and reps"),
                            ("bodyweight", "Reps with optional load"),
                            ("duration", "Duration"),
                            ("cardio", "Distance and duration"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lb", "lb")], max_length=3
                    ),
                ),
                (
                    "distance_unit",
                    models.CharField(
                        choices=[("km", "km"), ("mi", "mi")], max_length=3
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="workout_exercises",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["user", "performed_on"], name="workout_user_day_idx"
            ),
        ),
    ]
