# Generated by Django 6.0.3 on 2026-10-01 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0002_workout_workoutexercise_workout_workout_user_day_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("comment", models.TextField(blank=True, max_length=2000)),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.workoutexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weight__isnull", True),
                            ("weight__gte", 0),
                            _connector="OR",
                        ),
                        name="workout_set_weight_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("distance__isnull", True),
                            ("distance__gt", 0),
                            _connector="OR",
                        ),
                        name="workout_set_distance_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reps__isnull", True), ("reps__gt", 0), _connector="OR"
                        ),
                        name="workout_set_reps_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_seconds__isnull", True),
                            ("duration_seconds__gt", 0),
                            _connector="OR",
                        ),
                        name="workout_set_duration_positive",
                    ),
                ],
            },
        ),
    ]
