# Generated by Django 6.0.3 on 2026-10-02 07:51

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0003_workoutset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("display_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exercise_name", models.CharField(max_length=120)),
                ("category_name", models.CharField(max_length=120)),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("strength", "Weight and reps"),
                            ("bodyweight", "Reps with optional load"),
                            ("duration", "Duration"),
                            ("cardio", "Distance and duration"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lb", "lb")], max_length=3
                    ),
                ),
                (
                    "distance_unit",
                    models.CharField(
                        choices=[("km", "km"), ("mi", "mi")], max_length=3
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.routineday",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="routine_exercises",
                        to="workouts.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutRoutine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="routineday",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workouts.workoutroutine",
            ),
        ),
        migrations.CreateModel(
            name="RoutineSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "routine_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.routineexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weight__isnull", True),
                            ("weight__gte", 0),
                            _connector="OR",
                        ),
                        name="routine_set_weight_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("distance__isnull", True),
                            ("distance__gt", 0),
                            _connector="OR",
                        ),
                        name="routine_set_distance_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reps__isnull", True), ("reps__gt", 0), _connector="OR"
                        ),
                        name="routine_set_reps_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_seconds__isnull", True),
                            ("duration_seconds__gt", 0),
                            _connector="OR",
                        ),
                        name="routine_set_duration_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workoutroutine",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_workout_routine_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineday",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("routine"),
                name="unique_routine_day_name",
            ),
        ),
    ]
